### PR TITLE
Supersede #5 : Rework types

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Add minor modification : 
- style fixes
- slotting of dict subclasses
- more generic instantiation of pointer in ctypes backend (no test)

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
@mrh1997 if you are happy with my minor changes I will merge tomorrow and try to do a release.

**Comment by mrh1997** [comment]
I am back from holidays and can continue working on the project.
Since your changes are mainly cosmetic ones, I see no problem with them.

Regarding Patch  420ea4b: I see that you are very strict with handling of PEP8 (at least stricter than the original author of pyclibrary). I will try to take this into account in future and format my code to your requirements.

**Comment by MatthieuDartiailh** [comment]
Yes I try to enforce strictly PEP8. I think it is important to help the priject readability. Also avoiding trailing whitespace is a plus.
I will merge so that we can go on. I will try to make a minor release tomorrow.

**Comment by mrh1997** [comment]
This Pull Request also closes #6 (see commit d35b4ff, which is part if this PR)

**Pull request merged**
